### PR TITLE
Add docker example

### PR DESCRIPTION
**Pull request by frallax**
Add an example showing how to create a docker image that contains a Theia-based application with the vscode-trace-extension.

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I'm not sure if this contribution might fit-in better in repo `theia-trace-extension`? It's quite similar to the Docker example we already have in there, except this one here uses the `Trace Viewer for VSCode` from open-vsx, instead of using the `Theia Trace Viewer extension` from npm. 

Alternatively, since neither example application directly depend on the content in either repository, we might consider creating a new repo for them both, e.g. "Trace Viewer example applications" ?

@frallax  @bhufmann WDYT?

P.S. one potential argument to have this contribution in this repo here: we would need to try to confirm, but it's possible that the repo's tests, currently used against openvscode server running the vscode trace viewer, could be easily re-used on the containerized example Theia app running the same.

**Comment by frallax** [comment]
@marcdumais-work not sure if this can be used for the tests you mention above, mainly because the Theia application is not picking the "latest vscode-trace-extension master" but one of the released prebuilt vsix packages.

I think it belongs to this repo just to provide an example of how the artifacts produced by this repo can be used.
But this is just my opinion.

**Comment by marcdumais-work** [comment]
> not sure if this can be used for the tests you mention above, mainly because the Theia application is not picking the "latest vscode-trace-extension master" but one of the released prebuilt vsix packages.

I agree - but the goal would not be to test the trace viewer extension (it's already being tested), but rather to test the example application itself, to detect if it breaks. It's just a little bonus, if we can do that re-using the existing tests in the repo, like we did for the example application in theia-trace-extension.

**Comment by bhufmann** [comment]
> I'm not sure if this contribution might fit-in better in repo `theia-trace-extension`? It's quite similar to the Docker example we already have in there, except this one here uses the `Trace Viewer for VSCode` extension from open-vsx, instead of using the `Theia Trace Viewer extension` from npm.
> 
> Alternatively, since neither example application directly depend on the content in either repository, we might consider creating a new repo for them both, e.g. "Trace Viewer example applications" ?
> 
> @frallax @bhufmann WDYT?
> 
> P.S. one potential argument to have this contribution in this repo here: we would need to try to confirm, but it's possible that the repo's tests, currently used against openvscode server running the vscode trace viewer, could be easily re-used on the containerized example Theia app running the same.

I think that this docker example should be in the `theia-trace-extension` repository, since it's a Theia application. @frallax could you please contribute it there?

**Comment by frallax** [comment]
@bhufmann before following your advice, I'd like to understand the rationale of having this example in the theia-trace-extension repo. What is proposed in this pull request is an example of how to use the artifact created by this repo (vscode-trace-extension). That's why I contributed it to this repo.

The fact that the artifact is wrapped in a Theia application does not sound as a reason to have it in the theia-trace-extension repo. Maybe I should change it to a VSCode application, but then, would that really make a difference? Aren't we just changing the way we wrap an artifact created by the vscode-trace-extension repo?

Thanks for the explanation and help in advance!

**Pull request closed without merging**
