### PR TITLE
Release v0.3.0 (Minor)

### PR DESCRIPTION
**Pull request by bhufmann**
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
[RELEASE](https://github.com/pipe-cd/actions-gh-release)

The following 1 GitHub releases will be created once this pull request got merged.

## Release v0.3.0 with changes since v0.2.9

* Release v0.3.0 (Minor) [22fa5c7](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/22fa5c77dfcf377e587e052d001896253cf10de2)
* Upgrade traceviewer components [92a8b43](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/92a8b43a11463d9c38ae071c7e5cf5823b18f156)
* Select experiment when opening from open command [e1bfcee](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/e1bfcee1493621b060889a0e79c993c0748931d5)
* remove trailing commas [cddb22f](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/cddb22ff63b919fab13d897a149a5b3ae12eded6)

**Comment by bhufmann** [comment]
Tickets for license review for new traceviewer-base and traceviewer-react-components opened:
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17180
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17181

**Comment by marcdumais-work** [comment]
> X npm/npmjs/-/traceviewer-base/0.4.2, 
X npm/npmjs/-/traceviewer-react-components/0.4.2

We have the new components above not passing the license check. The license check [passes](https://github.com/eclipse-cdt-cloud/theia-trace-extension/actions/runs/11820514031) in in their own repos (theia-trace-extension), so we know there is no problem - we can have them approved but no need to wait before publishing this new release.

**Review by marcdumais-work — APPROVED** [review]
LGTM, thanks @bhufmann !

**Pull request merged**
