### PR TITLE
Migrate zoom and undo toolbar buttons

### PR DESCRIPTION
**Pull request by hriday-panchasara**
- Added undo/redo buttons
- Added zoom/in out buttons
- Using built-in icons for toolbar buttons
- Remove unused assets

Helps fix https://github.com/eclipse-cdt-cloud/vscode-trace-extension/issues/117

Working on separate patches to integrate shortcuts and marker menus
Screen Shot 2023-05-19 at 10 27 46 AM

Screen Shot 2023-05-19 at 10 28 10 AM

### CODE REVIEW

**Review by hoangphamEclipse — CHANGES_REQUESTED** [review]
Thank you for the PR. Looks like we have a merge conflict, can you take a look at it?

Also @bhufmann the icons of the Redo/Undo buttons are not the same as the Theia Trace Extension. Is this alright or should we opt for the same ones?

**Comment by bhufmann** [comment]
> Thank you for the PR. Looks like we have a merge conflict, can you take a look at it?
> 
> Also @bhufmann the icons of the Redo/Undo buttons are not the same as the Theia Trace Extension. Is this alright or should we opt for the same ones?

For the zoom buttons I'm ok to change it. However, the used buttons for undo/redo are buttons usually used for debugging actions (debug-step-back and debug-step-over). I think we should not use the same ones for undo/redo so that they don't get confused with debugging actions.

**Comment by hriday-panchasara** [comment]
> > Thank you for the PR. Looks like we have a merge conflict, can you take a look at it?
> > Also @bhufmann the icons of the Redo/Undo buttons are not the same as the Theia Trace Extension. Is this alright or should we opt for the same ones?
> 
> @hriday-panchasara The used buttons for undo/redo are buttons usually used for debugging actions (debug-step-back and debug-step-over). I think we should not use the same ones for undo/redo so that they don't get confused with debugging actions.
> 
> I also noticed that the help info for the shortcuts that is being prepared in [eclipse-cdt-cloud/theia-trace-extension#978](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/978) to be used in vscode-trace-extension shows the original icons. Maybe, we should also keep the zoom buttons, unless we change the help info.

Updated the undo/redo icons.

**Comment by bhufmann** [comment]
@hriday-panchasara did you notice this previous comment about the zoom buttons:

"I also noticed that the help info for the shortcuts that is being prepared in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/978 to be used in vscode-trace-extension shows the original icons. Maybe, we should also keep the zoom buttons, unless we change the help info. "

**Comment by hriday-panchasara** [comment]
> @hriday-panchasara did you notice this previous comment about the zoom buttons?
> 
> "I also noticed that the help info for the shortcuts that is being prepared in [eclipse-cdt-cloud/theia-trace-extension#978](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/978) to be used in vscode-trace-extension shows the original icons. Maybe, we should also keep the zoom buttons, unless we change the help info. "

Updated the zoom icons as well

**Review by bhufmann — APPROVED** [review]
LGTM. Thanks for the contribution.

**Review by hoangphamEclipse — CHANGES_REQUESTED** [review]
Hi @hriday-panchasara, I think the zoom in and zoom out icons are swapped.

image

**Comment by hriday-panchasara** [comment]
> Hi @hriday-panchasara, I think the zoom in and zoom out icons are swapped. I hovered on the + icon but it says zoom out instead. In the original photo, zoom out was on the right and zoom in was on the left.
> 
> image

Good catch! I've updated the icon references

**Review by hoangphamEclipse — APPROVED** [review]
LGTM

**Pull request merged**
